// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNXVnOFZDtQ6Pv04oA0rr7KXyjCNnC68',
    appId: '1:724404965241:android:0fa22f13cbab57478869a8',
    messagingSenderId: '724404965241',
    projectId: 'findex-295aa',
    storageBucket: 'findex-295aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT8z_6tr_B3vSW0IxkEAAigGpxOMi6cjY',
    appId: '1:724404965241:ios:8bf629476532e1a68869a8',
    messagingSenderId: '724404965241',
    projectId: 'findex-295aa',
    storageBucket: 'findex-295aa.firebasestorage.app',
    iosBundleId: 'com.example.findex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT8z_6tr_B3vSW0IxkEAAigGpxOMi6cjY',
    appId: '1:724404965241:ios:8bf629476532e1a68869a8',
    messagingSenderId: '724404965241',
    projectId: 'findex-295aa',
    storageBucket: 'findex-295aa.firebasestorage.app',
    iosBundleId: 'com.example.findex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtzCmOGJA-P773W-CKBCyvl9o1suDx8vM',
    appId: '1:724404965241:web:5a488f7b5c1f8eab8869a8',
    messagingSenderId: '724404965241',
    projectId: 'findex-295aa',
    authDomain: 'findex-295aa.firebaseapp.com',
    storageBucket: 'findex-295aa.firebasestorage.app',
    measurementId: 'G-SYV72BG6RF',
  );
}
